#!/usr/bin/env node

const fs = require("fs");
const util = require("util");
const childProcessExec = require("child_process").exec;
const GIT_GRAFT_CONFIG = require("../../git-graft.json");

const BRANCH_CONTRACT = RegExp(
  `(${GIT_GRAFT_CONFIG.branchTypes})\/${GIT_GRAFT_CONFIG.branchPattern}`,
  GIT_GRAFT_CONFIG.regExFlag || "gim"
);
const CODE_COMMIT_CONTRACT = RegExp(
  GIT_GRAFT_CONFIG.branchPattern,
  GIT_GRAFT_CONFIG.regExFlag || "gim"
);

const TIMEOUT_THRESHOLD = 5000;

const exec = util.promisify(childProcessExec);
const commitMessage = fs.readFileSync(process.argv[2], "utf8").trim();

prependBranchToCommit();
hookEscapeHatch();

async function prependBranchToCommit() {
  let branchName = "";
  try {
    branchName = await getCurrentBranch();
    checkBranchValidity(branchName);
  } catch (e) {
    handleGitBranchCommandError(e);
  }
  fs.writeFileSync(process.argv[2], `${branchName}: ${commitMessage}`);

  checkCommitValidity(fs.readFileSync(process.argv[2], "utf8").trim());
  process.exit(0);
}

async function getCurrentBranch() {
  const branchesOutput = await exec("git branch");
  if (branchesOutput.stderr) {
    throw new Error(branchesOutput.stderr);
  }
  return branchesOutput.stdout
    .split("\n")
    .find((str) => str.trim().charAt(0) === "*")
    .trim()
    .substring(2);
}

function checkBranchValidity(branchName) {
  if (!BRANCH_CONTRACT.test(branchName)) {
    handleBadBranchName();
  }
}

function checkCommitValidity(commitMessage) {
  if (!CODE_COMMIT_CONTRACT.test(commitMessage)) {
    handleBadCommitMessage();
  }
}

function handleGitBranchCommandError(e) {
  console.log(
    `'Error executing "git branch" command' \n`,
    `${e.getMessage()} \n`,
    `----, \n`,
    `Your commit will be rejected. This script will terminate.`
  );
  process.exit(1);
}

function handleBadBranchName() {
  console.log(
    `There is something wrong with your branch name \n`,
    `branch names in this project must adhere to this pattern: ${BRANCH_CONTRACT} \n`,
    `Your commit will be rejected. You should rename your branch to a valid name, based on your configurations check git-graft.json`
  );
  process.exit(1);
}

function handleBadCommitMessage() {
  console.log(
    `There is something wrong with your commit message \n`,
    `it should start with a valid Jira issue code, followed by a dash, thus adhering to this contract: ${CODE_CONTRACT} \n`,
    `your commit will be rejected. Please re-commit your work again with a proper commit message.`
  );
  process.exit(1);
}

function hookEscapeHatch() {
  setTimeout(() => {
    console.log(
      `Git Graft Hook Timeout. If you see this, something bad happened in your pre-commit hook. \n`,
      `Your commit will be rejected.`
    );
    process.exit(1);
  }, TIMEOUT_THRESHOLD);
}
